### PR TITLE
Clean up temporary files in tests. Fixes #8.

### LINKED ISSUE #8: Clean up temporary files from running tests
Note https://github.com/JuliaLang/julia/issues/9053, `tempname` creates temporary files on Windows. That should be fixed in base eventually, but there are other constructs that can be used instead - `mktemp() do` etc.

### PR DESCRIPTION
**Pull request by timholy**
CC @tkelman (sorry this got forgotten).

### CODE REVIEW

**Comment by timholy** [comment]
Sigh. Now that we fixed one 0.6 problem (ColorTypes), we get to discover others. https://github.com/JuliaMath/FixedPointNumbers.jl/pull/74.

Someday, the whole Colors/Images suite *will* pass on 0.6.

**Comment by tkelman** [comment]
did you formerly have appveyor running here?

**Comment by timholy** [comment]
Annoyingly, JuliaImages doesn't show up among the list of projects that I can add to AppVeyor. Almost everything else does. Any ideas?

**Comment by tkelman** [comment]
Very odd. You might need to log out then log back in, but select a different account in the dropdown you get

**Comment by timholy** [comment]
I've tried all the ones I have.

**Comment by tkelman** [comment]
May need to grant it org privileges in the github settings?

**Comment by Evizero** [comment]
You may need to click some "sync" button somewhere. I have had such issues before on CI related sites where packages or an org didn't show up.

**Comment by timholy** [comment]
Can't find a sync button to push on AppVeyor. Checking against JuliaGraphics (which does show up), there don't seem to be any org settings for AppVeyor. However, there *is* one big difference: in JuliaImages, under "Third-party access" it seems we have access restrictions in place. AppVeyor is one of the approved applications, however. I just tried "denying" it and then re-approving it. That didn't seem to change anything on the AppVeyor side.

Crazy to turn off access restrictions?

Because it took me surprisingly long to find these, I'm leaving some breadcrumbs:
https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/
https://help.github.com/articles/approving-third-party-applications-for-your-organization/

Is it crazy to delete that and try again? (I'm forgetting how one goes about adding a third-party app---

**Comment by SimonDanisch** [comment]
I can confirm that all the usual tricks didn't help :(

**Comment by tkelman** [comment]
Could also email support@appveyor.com (or maybe now it's team@appveyor.com?), it's the weekend but worth a shot anyway

**Comment by timholy** [comment]
Email sent.

**Comment by timholy** [comment]
Fixed thanks to @FeodorFitsner. It was enabled for AppVeyor but it had never been requested for AppVeyorCI. I've turned it on for most of the repos, but let me know if there are any missing.

**Comment by tkelman** [comment]
Lovely. Could we fire off a build on master here?

**Comment by SimonDanisch** [comment]
did just that (I think) ;)

**Comment by timholy** [comment]
With brand-new segfaulting on 0.5 and brand-new ambiguities in FixedPointNumbers on  the latest nightly (https://github.com/JuliaMath/FixedPointNumbers.jl/pull/74), this is unlikely to be informative. Unless magically https://github.com/JuliaLang/METADATA.jl/pull/7926 gets merged before the 0.6 tests fire.

**Comment by timholy** [comment]
How does so much fall apart in 24 hours? :frowning:

**Comment by tkelman** [comment]
I'm mostly wanting to see if windows is able to get through a run, given permission requirements there

**Comment by timholy** [comment]
Reasonable thing to want to know. I already tested that on a different repo (https://github.com/JuliaImages/ImageAxes.jl/pull/14), which happened to be first alphabetically.

**Pull request merged**
