### PR TITLE
Expands imfilter documentation with more details and examples

### PR DESCRIPTION
**Pull request by zygmuntszpak**

### CODE REVIEW

**Comment by Evizero** [comment]
Oh wow, thats quite an effort you put into this. 

how does it behave in a terminal?

**Comment by Evizero** [comment]
does this PR overlap with #56 ?

**Comment by Evizero** [comment]
also, I may have just introduced the merge conflict by merging #55 . sorry about that, but that PR seemed quite uncontroversial

**Comment by zygmuntszpak** [comment]
I've resolved the merge conflict in the latest commit. As anticipated, some of the LaTeX matrices are not easy to understand from the REPL. However, I think the problem is best resolved by writing a package to render LaTeX formulas in ASCII.  See [this discussion](https://math.stackexchange.com/questions/149303/software-to-render-formulas-to-ascii-art#156208) for example. I've put up an honours project at my university for someone to work on this---will have to see if anyone takes it up. I may give it a go sometime this year if no one else takes up the project. 

This commit only makes changes to the imfilter function so it is orthogonal to #54 .

**Comment by zygmuntszpak** [comment]
ping @Evizero

**Comment by Evizero** [comment]
Thanks!

**Pull request merged**
