### PR TITLE
Preview PRs in docs

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by timholy** [comment]
Cool, I was unaware this was possible. Where does one find the preview?

**Comment by asinghvi17** [comment]
Unfortunately, the preview won't be for this PR (since it's from an external source).  For internal PRs, the URL is juliaimages.org/ImageFiltering.jl/previews/PR162 (or whatever the PR number is).

**Comment by timholy** [comment]
Nice! We will probably want to add that info to https://github.com/JuliaImages/Images.jl/blob/master/CONTRIBUTING.md too.

**Comment by johnnychen94** [comment]
FYI, I've already set it up in the juliaimages docs, e.g., https://github.com/JuliaImages/juliaimages.github.io/pull/115

**Pull request merged**
