### PR TITLE
Swap symmetric and reflect in doc

### PR DESCRIPTION
**Pull request by innerlee**
Fix https://github.com/JuliaImages/ImageFiltering.jl/issues/84

### CODE REVIEW

**Comment by jw3126** [comment]
Can you add a doctest, like https://github.com/JuliaImages/ImageFiltering.jl/issues/84#issuecomment-438362454

**Comment by innerlee** [comment]
There is no doctest in this repo. Maybe you mean a test?

**Comment by jw3126** [comment]
Oh wow it seems you are right, I can't spot any doctests. But I guess that is because this package is older then `Documenter.jl` reasons and it is fine to add them @timholy ?

**Comment by timholy** [comment]
Yes, it would be great to add doctests. And indeed this package predates Documenter.

**Pull request merged**
